name: "Docker cache demo"
on:
  workflow_dispatch:
jobs:
  pull_images:
    runs-on: gha-runner-scale-set
    steps:
      - name: Pull images
        run: |
          docker pull alpine:3.12
          docker pull postgres:13.15
          docker pull grafana/grafana:main
          docker pull vitess/lite:latest
